image: atlassian/default-image:4

pipelines:
  branches:
    master:
      - step:
          script:
            - ssh-keyscan git.wpengine.com >> ~/.ssh/known_hosts
            - git push git@git.wpengine.com:kneat.git master
            - echo "Deployment to production completed"

    dev:
      - step:
          script:
            - ssh-keyscan git.wpengine.com >> ~/.ssh/known_hosts
            - git push git@git.wpengine.com:kneatstg.git dev
            - echo "Deployment to development completed"