image: atlassian/default-image:4

pipelines:
  branches:
    dev:
      - step:
          name: Deploy to Dev
          script:
          - pipe: wpengine/wpe-site-deploy:v1
            variables:
              WPE_SSHG_KEY_PRIVATE: $WPE_SSHG_KEY_PRIVATE
              WPE_ENV: kneatstg
    master:
      - step:
          name: Deploy to Production
          script:
          - pipe: wpengine/wpe-site-deploy:v1
            variables:
              WPE_SSHG_KEY_PRIVATE: $WPE_SSHG_KEY_PRIVATE
              WPE_ENV: kneat
    